USE sphelp;
/*create table*/
CREATE TABLE IF NOT EXISTS `sphelp`.`Usuario` (
  `_i` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `_s` VARCHAR(50) NOT NULL DEFAULT 'ativo' COMMENT '',
  `_d` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `login` VARCHAR(50) NOT NULL COMMENT '',
  `senha` VARCHAR(255) NOT NULL COMMENT '',
  `nome` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`_i`)  COMMENT '',
  UNIQUE INDEX `_i_UNIQUE` (`_i` ASC)  COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '')
ENGINE = InnoDB