USE sphelp;
/*create table*/
CREATE TABLE IF NOT EXISTS `sphelp`.`Versao` (
  `_i` INT NOT NULL COMMENT '',
  `_d` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `numero` VARCHAR(50) NOT NULL COMMENT '',
  `implementacao` LONGTEXT NULL COMMENT '',
  `correcao` LONGTEXT NULL COMMENT '',
  PRIMARY KEY (`_i`)  COMMENT '',
  UNIQUE INDEX `_i_UNIQUE` (`_i` ASC)  COMMENT '')
ENGINE = InnoDB