@ECHO OFF
ECHO Criando banco de dados...
mysql -u root < %cd%\scripts\001-create_database_sphelp.sql
ECHO Criando tabela Usuario...
mysql -u root < %cd%\scripts\002-create_table_Usuario.sql
ECHO Criando tabela Historico...
mysql -u root < %cd%\scripts\003-create_table_Historico.sql
ECHO Criando tabela Configuracao...
mysql -u root < %cd%\scripts\004-create_table_Configuracao.sql
ECHO Criando tabela TipoContato...
mysql -u root < %cd%\scripts\005-create_table_TipoContato.sql
ECHO Criando tabela ClasseContato...
mysql -u root < %cd%\scripts\006-create_table_ClasseContato.sql
ECHO Criando tabela TipoEndereco...
mysql -u root < %cd%\scripts\007-create_table_TipoEndereco.sql
ECHO Criando tabela Cliente...
mysql -u root < %cd%\scripts\008-create_table_Cliente.sql
ECHO Criando tabela ClienteEndereco...
mysql -u root < %cd%\scripts\009-create_table_ClienteEndereco.sql
ECHO Criando tabela ClienteContato...
mysql -u root < %cd%\scripts\010-create_table_ClienteContato.sql
ECHO Criando tabela Chamado...
mysql -u root < %cd%\scripts\011-create_table_Chamado.sql
ECHO Criando tabela Atendimento...
mysql -u root < %cd%\scripts\012-create_table_Atendimento.sql
ECHO Criando tabela AtendimentoArquivo...
mysql -u root < %cd%\scripts\013-create_table_AtendimentoArquivo.sql
ECHO Criando tabela UsuarioSessao...
mysql -u root < %cd%\scripts\014-create_table_UsuarioSessao.sql
ECHO Inserindo dados na tabela ClasseContato...
mysql -u root < %cd%\scripts\015-insert_into_ClasseContato.sql
ECHO Inserindo dados na tabela TipoContato...
mysql -u root < %cd%\scripts\016-insert_into_TipoContato.sql
ECHO Inserindo dados na tabela TipoEndereco...
mysql -u root < %cd%\scripts\017-insert_into_TipoEndereco.sql
ECHO Inserindo dados na tabela Usuario...
mysql -u root < %cd%\scripts\018-insert_into_Usuario.sql
ECHO Execucao de Scripts finalizada.
PAUSE